// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FakeCreateForModels() {
  return window['go']['main']['App']['FakeCreateForModels']();
}

export function SaveIcon(arg1, arg2) {
  return window['go']['main']['App']['SaveIcon'](arg1, arg2);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function StopBackup(arg1) {
  return window['go']['main']['App']['StopBackup'](arg1);
}
