// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {uuid} from '../models';

export function SelectDirectory(arg1:string):Promise<string>;

export function StopBackup(arg1:uuid.UUID):Promise<void>;
