// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckRepository(arg1) {
  return window['go']['main']['App']['CheckRepository'](arg1);
}

export function GetBackupJobs() {
  return window['go']['main']['App']['GetBackupJobs']();
}

export function InitializeRepository(arg1) {
  return window['go']['main']['App']['InitializeRepository'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function Snapshots(arg1) {
  return window['go']['main']['App']['Snapshots'](arg1);
}

export function StopBackup(arg1) {
  return window['go']['main']['App']['StopBackup'](arg1);
}
