// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckRepository(arg1) {
  return window['go']['main']['App']['CheckRepository'](arg1);
}

export function GetBackupJobs() {
  return window['go']['main']['App']['GetBackupJobs']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InitializeRepository(arg1) {
  return window['go']['main']['App']['InitializeRepository'](arg1);
}

export function RescheduleBackups() {
  return window['go']['main']['App']['RescheduleBackups']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function Settings() {
  return window['go']['main']['App']['Settings']();
}

export function Snapshots(arg1) {
  return window['go']['main']['App']['Snapshots'](arg1);
}

export function StopBackup(arg1) {
  return window['go']['main']['App']['StopBackup'](arg1);
}
