name: Build
run-name: ${{ github.ref_name }} - Build
on:
  push:
    tags:
      - "*"
jobs:
  build:
    strategy:
    # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: 'resticity-Linux-${{ github.ref_name }}'
            platform:  'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'Resticity-Windows-Portable-${{ github.ref_name }}.exe'
            platform:  'windows/amd64'
            os: 'windows-latest'
          # - name: 'Resticity'
          #   platform:  'darwin/universal'
          #   os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false
          go-version: '1.21'
      - uses: actions/upload-artifact@v3
        with:
          name: Wails Build 
          path: |
            */bin/
            *\bin\*
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@master
        with:
          path: |
            */bin/
            *\bin\*
      - uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          files: |
            */bin/*