name: container
run-name: ${{ github.ref_name }} - Publishing Container 
on:
  release:
    types: [published]
jobs:
  publish-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish Container
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}  # it will be lowercased internally
          github_token: ${{ secrets.GH_TOKEN }}